export const songs = [
    '/trackerfiles/estrayk - her 10.mod',
    '/trackerfiles/JosSs - Extra Life.mod',
    '/trackerfiles/loonie and ramjam - gary & denise.mod',
    '/trackerfiles/tempest - acidjazzed evening.mod',
    '/trackerfiles/4mat - black lipstick.xm',
    '/trackerfiles/4mat - blank page.xm',
    '/trackerfiles/4mat - broken heart.XM',
    '/trackerfiles/4mat - eternity.xm',
    '/trackerfiles/4mat - rose.xm',
    '/trackerfiles/4mat - Vertical.xm',
    '/trackerfiles/AceMan - realize the truth.xm',
    '/trackerfiles/algar - imorn e en annan dag.xm',
    '/trackerfiles/anachro - a sad touch.xm',
    '/trackerfiles/anachro - bunnyboobz.xm',
    '/trackerfiles/Anders Dator, Felix Dator - 2 x the SQUAREbeam.xm',
    '/trackerfiles/Anders Dator, Felix Dator - no name level no. 1.xm',
    "/trackerfiles/arachno - granny's mambo.xm",
    '/trackerfiles/arachno - just another....xm',
    "/trackerfiles/arachno - Sasja's teddy.xm",
    '/trackerfiles/arachno - tip of my tongue.xm',
    '/trackerfiles/arachno & jockson - solnedgang.xm',
    '/trackerfiles/Attraction - Maran Project.xm',
    "/trackerfiles/bboll - mr spock's cryo bed.xm",
    '/trackerfiles/cerror - close encounter.xm',
    '/trackerfiles/cerror - Jet stream.xm',
    '/trackerfiles/cerror - sea side blues.xm',
    '/trackerfiles/chavez - ninja bolognese.xm',
    '/trackerfiles/dualtrax - orion spaceforce23.xm',
    '/trackerfiles/Dubmood - 3D Galax.xm',
    '/trackerfiles/Dubmood - Botkyrka Sidekickers.xm',
    '/trackerfiles/Dubmood - Introchip no. 14 BETAFLUX.XM',
    '/trackerfiles/Dubmood - Paradox no. 3.xm',
    '/trackerfiles/falcon - spineless_.xm',
    '/trackerfiles/Fearofdark - Get A Brain Morans.xm',
    '/trackerfiles/Funky Fish - R2-D2.xm',
    '/trackerfiles/Funky Fish and raina - artificial sweetener.xm',
    '/trackerfiles/Ghidorah - Good night Mr. Pung.xm',
    '/trackerfiles/gusse & keyg & loonie - synergetic.xm',
    '/trackerfiles/HyoChan - sleepy sunflower.xm',
    '/trackerfiles/Jakim - Valium candies.xm',
    '/trackerfiles/JosSs - Eklipse.xm',
    '/trackerfiles/JosSs - Pixeltropia.xm',
    '/trackerfiles/JosSs - Sweetest Sin.XM',
    '/trackerfiles/JosSs - Xs EdzesSs.xm',
    '/trackerfiles/joule - independent.xm',
    '/trackerfiles/joule & ko0x - caroline in neon.xm',
    '/trackerfiles/joule & malmen - one way heart.xm',
    '/trackerfiles/Kapten Floede - Magic Cookie Maker.xm',
    '/trackerfiles/ko0x - caramel condition.xm',
    '/trackerfiles/ko0x - zenon.xm',
    '/trackerfiles/lesnik - bother me.xm',
    '/trackerfiles/lesnik - rob mat reyn pink.xm',
    '/trackerfiles/look & zalza - little computer boy.xm',
    '/trackerfiles/loonie - the man in the moon.xm',
    '/trackerfiles/magma, wabe, dark raccoons - Blinded Monarch.xm',
    '/trackerfiles/malmen & joule - tomorrow without you.xm',
    '/trackerfiles/matrix cubed - home.xm',
    '/trackerfiles/moh - kontaktproblem.xm',
    '/trackerfiles/motherchip - portello.xm',
    '/trackerfiles/mrdeath - Hyperdrive Motion.xm',
    '/trackerfiles/MrGamer - For My Friends.xm',
    '/trackerfiles/MrGamer - Hostlov.xm',
    '/trackerfiles/MrGamer - Oskars Skarmslackare.xm',
    '/trackerfiles/MrGamer - Yes, I see.xm',
    '/trackerfiles/Mystic Cloud - Obsession.xm',
    '/trackerfiles/Nagz - x  0  (.)  .  c.xm',
    '/trackerfiles/ogg - lost.xm',
    '/trackerfiles/pk - Chip orgie.xm',
    '/trackerfiles/radix - the mission.xm',
    '/trackerfiles/radix & loonie - kookoo.xm',
    '/trackerfiles/radix & xyce - Rainbow Dash.xm',
    '/trackerfiles/raina - slumberjack.xm',
    '/trackerfiles/raina - smile.xm',
    '/trackerfiles/raina - sumsong.xm',
    '/trackerfiles/rez+kenet - unreeeal superhero 3.xm',
    '/trackerfiles/Saxxon Pike - Broken.xm',
    '/trackerfiles/seablue - jason the spacecadet.xm',
    '/trackerfiles/skuter - .mr. saw.xm',
    '/trackerfiles/SofT MANiAC - i NEEd Y0uR L0vE!.xm',
    '/trackerfiles/tequila - stefan missar bussan.xm',
    '/trackerfiles/tone - siberiada.XM',
    '/trackerfiles/UNKNOWN - alone in the scene.xm',
    '/trackerfiles/UNKNOWN - reloaded intro music.XM',
    '/trackerfiles/Unstruct - Above and beyond.xm',
    '/trackerfiles/xerxes - untitled.xm',
    '/trackerfiles/xyce - la cherie.xm',
    '/trackerfiles/zalza - tekilla groove.xm',
    '/trackerfiles/Zalza - Tuborg Heaven.xm',
    '/trackerfiles/amgorb - randomizer 666.it',
    '/trackerfiles/Ceekayed - Layers.it',
    '/trackerfiles/Ceekayed - Wobbly Things.it',
    '/trackerfiles/laamaa - nelly in 8bit land.it',
    '/trackerfiles/Nightbeat - Winterstar.it',
    '/trackerfiles/Ojciec - Usteczka .it',
    '/trackerfiles/radix - something eating my mind.it',
    '/trackerfiles/radix & loonie - kookoo (GHOSTDESIGN_MIX).it',
    '/trackerfiles/silo7 - verZion.it',
    '/trackerfiles/tj technoiZ - too old.it',
    '/trackerfiles/vibe - I should quit chipping.it',
    '/trackerfiles/vince kaichan - ama no gawa.it',
  ]